# Client Dockerfile

# Step 1: Build the Vite app
FROM node:16 AS build

WORKDIR /app

COPY package.json package-lock.json ./ 
RUN npm install

COPY . .

RUN npm run build

# Step 2: Serve the built files with NGINX
FROM nginx:alpine

# Copy the build files from the first stage (use `dist` instead of `build` for Vite)
COPY --from=build /app/dist /usr/share/nginx/html

# Expose the necessary port for client-side
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
