name: Build and Deploy to DockerHub

on:
  push:
    branches:
      - main  # Trigger when code is pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Using the latest Ubuntu environment

    steps:
      
      - name: Check out the repository
        uses: actions/checkout@v3

      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Replace with your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Replace with your Docker Hub password or token

      
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      
      - name: Build and Push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

     
      - name: Clean up Docker images
        run: |
          docker system prune -af
