name: Manual Terraform Deployment

on:
  workflow_dispatch:  # Manual trigger

jobs:
  terraform:
    name: Deploy with Terraform
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Step 3: Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Import SG
      - name: Terraform Import SG
        run: terraform import aws_security_group.yappi_sg sg-0e464cd9acdc928ee

      # Step 6: Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Step 7: Terraform Apply (auto-approve is risky; use with care)
      - name: Terraform Apply
        run: terraform apply -auto-approve
